services:
  - type: web
    name: fan-server
    env: node
    plan: free
    buildCommand: |
      cd client && npm install && npm run build
      cd ../fan-server && npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
